- id: '1577555518352'
  alias: Home - Off
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.been_home
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id:
      - 14c52f1d72d94a29a745d0a400806c3a
      - e4cd392f3436439681504b0610b28b1d
      - 5c8d6d678e49498a9e77ff541ec6fad1
  - service: media_player.turn_off
    target:
      area_id:
      - 72f600fc787e479eaf6ce20ac1df415b
      device_id:
      - e2218f1596be472186f459e1f173c07c
      - 45806b6577db034d108d0ef352480539
      - 4bdf051aaa818b21fe2f85cdfc04629c
  - service: switch.turn_off
    target:
      area_id: a13da43aa35f4548a72c6e44312a414a
  - choose:
    - conditions:
      - condition: state
        entity_id: media_player.living_room_tv
        state: 'on'
      sequence:
      - service: media_player.turn_off
        target:
          device_id: 4f6d27b4523f3c8140647e69843d7b78
    default: []
  - service: media_player.media_stop
    target:
      entity_id: media_player.living_room
  mode: single
- id: '1577565166930'
  alias: Ringing Blinking Light - On
  description: ''
  trigger:
  - entity_id: sensor.in2023_phone_state
    platform: state
    to: ringing
  condition:
  - condition: zone
    entity_id: person.christian
    zone: zone.home
  - condition: device
    device_id: f6def5b1ec034a728acc95f4c119e782
    domain: light
    entity_id: light.ceiling_desk
    type: is_on
  action:
  - entity_id: script.1577563891032
    service: script.turn_on
  mode: single
- id: '1577565265648'
  alias: Ringing Blinking Light - Off
  description: ''
  trigger:
  - entity_id: sensor.in2023_phone_state
    platform: state
    to: ringing
  condition:
  - condition: zone
    entity_id: person.christian
    zone: zone.home
  - condition: device
    device_id: f6def5b1ec034a728acc95f4c119e782
    domain: light
    entity_id: light.ceiling_desk
    type: is_off
  action:
  - entity_id: script.1577564199944
    service: script.turn_on
  mode: single
- id: '1577565666489'
  alias: Home - On
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.been_home
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data: {}
    service: light.turn_on
    target:
      area_id: e4cd392f3436439681504b0610b28b1d
  mode: single
- id: '1577566232007'
  alias: Play Music - Ring
  description: ''
  trigger:
  - from: offhook
    platform: state
    to: idle
    entity_id: sensor.in2023_phone_state
  condition:
  - condition: zone
    entity_id: person.christian
    zone: zone.home
  - condition: state
    entity_id: media_player.spotify_christian_bilevits
    state: paused
  - condition: state
    entity_id: sensor.ac2003_telefonstatus
    state: offhook
  action:
  - service: script.1577565978977
  mode: single
- id: '1577566320646'
  alias: Pause Music - Ring
  description: ''
  trigger:
  - platform: state
    to: offhook
    entity_id: sensor.in2023_phone_state
  condition:
  - condition: zone
    entity_id: person.christian
    zone: zone.home
  - condition: state
    entity_id: media_player.spotify_christian_bilevits
    state: playing
  action:
  - service: script.1577566038402
  mode: single
- id: '1585561512813'
  alias: Auto turn off - Crapper
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: be9974f111dc5798cffa01d41de08cff
    entity_id: light.toilet
    domain: light
    for:
      hours: 0
      minutes: 45
      seconds: 0
      milliseconds: 0
  condition:
  - condition: device
    type: is_on
    device_id: be9974f111dc5798cffa01d41de08cff
    entity_id: light.toilet
    domain: light
  action:
  - type: turn_off
    device_id: be9974f111dc5798cffa01d41de08cff
    entity_id: light.toilet
    domain: light
  mode: single
- id: '1585585858395'
  alias: Turn off ceiling - Night
  description: ''
  trigger:
  - below: '-50'
    entity_id: sensor.circadian_values
    for: 00:00:00
    platform: numeric_state
  - device_id: ddcf63714c2a4c50be1e6a101708ec10
    domain: light
    entity_id: light.ceiling_bed
    for:
      hours: 0
      minutes: 0
      seconds: 1
    platform: device
    type: turned_on
  - device_id: f6def5b1ec034a728acc95f4c119e782
    domain: light
    entity_id: light.ceiling_desk
    for:
      hours: 0
      minutes: 0
      seconds: 1
    platform: device
    type: turned_on
  - device_id: 6d1cf939784f4140b69a43dbcc6d077b
    domain: light
    entity_id: light.ceiling_sofa
    for:
      hours: 0
      minutes: 0
      seconds: 1
    platform: device
    type: turned_on
  condition:
  - below: '-50'
    condition: numeric_state
    entity_id: sensor.circadian_values
  - condition: state
    entity_id: switch.circadian_lighting_circadian_brightness
    state: 'on'
  action:
  - device_id: ddcf63714c2a4c50be1e6a101708ec10
    domain: light
    entity_id: light.ceiling_bed
    type: turn_off
  - device_id: f6def5b1ec034a728acc95f4c119e782
    domain: light
    entity_id: light.ceiling_desk
    type: turn_off
  - device_id: 6d1cf939784f4140b69a43dbcc6d077b
    domain: light
    entity_id: light.ceiling_sofa
    type: turn_off
- id: '1605973279828'
  alias: Toilet - Sensor
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: db06330462a9c0236cf4942a2bf2f843
    entity_id: binary_sensor.toilet_sensor
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: input_boolean.toilet_manual
    state: 'off'
  action:
  - choose:
    - conditions:
      - condition: time
        after: '23:00'
        before: 07:00
      sequence:
      - service: light.turn_on
        data:
          kelvin: 2262
          brightness_pct: 1
          transition: 2
        entity_id: light.toilet
    default:
    - service: light.turn_on
      data:
        kelvin: 2747
        brightness_pct: 100
        transition: 2
      entity_id: light.toilet
  mode: single
- id: '1605973464792'
  alias: Toilet - Sensor - Stopped
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: db06330462a9c0236cf4942a2bf2f843
    entity_id: binary_sensor.toilet_sensor
    domain: binary_sensor
    for:
      hours: 0
      minutes: 4
      seconds: 0
  condition:
  - condition: time
    after: 07:00
    before: '23:00'
  - condition: device
    type: is_on
    device_id: be9974f111dc5798cffa01d41de08cff
    entity_id: light.toilet
    domain: light
  - condition: state
    entity_id: input_boolean.toilet_manual
    state: 'off'
  action:
  - service: light.turn_on
    data:
      kelvin: 2747
      brightness_pct: 50
      transition: 2
    entity_id: light.toilet
  mode: single
- id: '1605973519068'
  alias: Toilet - Sensor - Off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: db06330462a9c0236cf4942a2bf2f843
    entity_id: binary_sensor.toilet_sensor
    domain: binary_sensor
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.toilet_manual
    state: 'off'
  action:
  - service: light.turn_off
    data:
      transition: 2
    entity_id: light.toilet
  mode: single
- id: '1606118844897'
  alias: Toilet - Manual Trigger - On
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: be9974f111dc5798cffa01d41de08cff
    entity_id: light.toilet
    domain: light
    for:
      hours: 0
      minutes: 0
      seconds: 2
  condition:
  - type: is_no_motion
    condition: device
    device_id: db06330462a9c0236cf4942a2bf2f843
    entity_id: binary_sensor.toilet_sensor
    domain: binary_sensor
  - condition: state
    entity_id: input_boolean.toilet_manual
    state: 'off'
  action:
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.toilet_manual
  - type: turn_on
    device_id: be9974f111dc5798cffa01d41de08cff
    entity_id: light.toilet
    domain: light
    brightness_pct: 100
  mode: single
- id: '1606119045624'
  alias: Toilet - Manual Trigger - Off
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: be9974f111dc5798cffa01d41de08cff
    entity_id: light.toilet
    domain: light
  condition:
  - condition: state
    entity_id: input_boolean.toilet_manual
    state: 'on'
  action:
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.toilet_manual
  mode: single
- id: '1607243658672'
  alias: Welcome Home - Christian
  description: ''
  trigger:
  - platform: zone
    entity_id: person.christian
    zone: zone.home
    event: enter
  condition: []
  action:
  - delay: '60'
  - service: script.welcome_home_christian
    data:
      name: Christian
    entity_id: script.welcome_home_christian
  mode: single
- id: '1607244394687'
  alias: Welcome Home - Felicia
  description: ''
  trigger:
  - platform: zone
    entity_id: person.felicia
    zone: zone.home
    event: enter
  condition: []
  action:
  - delay: '60'
  - service: script.welcome_home_christian
    data:
      name: Felicia
  mode: single
- id: '1611609131335'
  alias: Gaming - On
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.stadia_a2c2
    to: home
    from: not_home
  condition: []
  action:
  - service: media_player.turn_on
    target:
      device_id: 4f6d27b4523f3c8140647e69843d7b78
  - wait_for_trigger:
    - platform: device
      type: turned_on
      device_id: 4f6d27b4523f3c8140647e69843d7b78
      entity_id: remote.living_room_tv
      domain: remote
      for:
        hours: 0
        minutes: 0
        seconds: 2
        milliseconds: 0
  - service: media_player.select_source
    target:
      device_id: 4f6d27b4523f3c8140647e69843d7b78
    data:
      source: HDMI 2
  mode: single
- id: '1611609215573'
  alias: Gaming - Off
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.stadia_a2c2
    from: home
    to: not_home
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.led
  mode: single
- id: '1613827164291'
  alias: Felicia Paus Music
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.ac2003_telefonstatus
    to: offhook
  condition:
  - condition: zone
    entity_id: person.felicia
    zone: zone.home
  - condition: device
    device_id: 4bdf051aaa818b21fe2f85cdfc04629c
    domain: media_player
    entity_id: media_player.living_room
    type: is_playing
  action:
  - service: media_player.media_pause
    data: {}
    target:
      device_id: 4bdf051aaa818b21fe2f85cdfc04629c
  mode: single
- id: '1613827263890'
  alias: Felicia Play Music
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.ac2003_telefonstatus
    from: offhook
    to: idle
  condition:
  - condition: zone
    entity_id: person.felicia
    zone: zone.home
  - condition: device
    device_id: 4bdf051aaa818b21fe2f85cdfc04629c
    domain: media_player
    entity_id: media_player.living_room
    type: is_paused
  - condition: state
    entity_id: sensor.in2023_phone_state
    state: offhook
  action:
  - service: media_player.media_play
    data: {}
    target:
      device_id: 4bdf051aaa818b21fe2f85cdfc04629c
  mode: single
- id: '1618177610102'
  alias: Night Light - Stairs - On
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 1676fc84015df0dfd79488157a70b6c1
    entity_id: binary_sensor.stairs_sensor
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: input_boolean.night_mode
    state: 'on'
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.adaptive_lighting_adapt_brightness_kitchen
  - type: turn_on
    device_id: ea02134afc6d69b0da1921c9af86bcb5
    entity_id: light.ceiling_toilet
    domain: light
    brightness_pct: 2
  mode: single
- id: '1618177885328'
  alias: Night Light - Kitchen - On
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: db06330462a9c0236cf4942a2bf2f843
    entity_id: binary_sensor.kitchen_sensor
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: input_boolean.night_mode
    state: 'on'
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.adaptive_lighting_adapt_brightness_kitchen
  - type: turn_on
    device_id: ea02134afc6d69b0da1921c9af86bcb5
    entity_id: light.ceiling_toilet
    domain: light
    brightness_pct: 2
  mode: single
- id: '1618178644833'
  alias: Night Light - Off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: db06330462a9c0236cf4942a2bf2f843
    entity_id: binary_sensor.kitchen_sensor
    domain: binary_sensor
    for:
      hours: 0
      minutes: 6
      seconds: 0
      milliseconds: 0
  condition:
  - type: is_no_motion
    condition: device
    device_id: db06330462a9c0236cf4942a2bf2f843
    entity_id: binary_sensor.kitchen_sensor
    domain: binary_sensor
  - condition: numeric_state
    attribute: brightness
    above: '1'
    below: '10'
    entity_id: light.ceiling_toilet
  - condition: state
    entity_id: input_boolean.night_mode
    state: 'on'
  action:
  - type: turn_off
    device_id: ea02134afc6d69b0da1921c9af86bcb5
    entity_id: light.ceiling_toilet
    domain: light
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: switch.turn_on
    target:
      entity_id: switch.adaptive_lighting_adapt_brightness_kitchen
  mode: single
- id: '1618230174554'
  alias: Night Mode - Toggle
  description: ''
  trigger:
  - platform: time
    at: '23:30'
  - platform: time
    at: 06:30
  condition: []
  action:
  - choose:
    - conditions:
      - condition: time
        after: '23:29'
        before: 06:29
      sequence:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.night_mode
    default:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.night_mode
  mode: single
- id: '1618341675693'
  alias: Been Home - On
  description: ''
  trigger:
  - platform: zone
    entity_id: person.christian
    zone: zone.home
    event: enter
  - platform: zone
    entity_id: person.felicia
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.been_home
  mode: single
- id: '1618341855293'
  alias: Been Home - Off
  description: ''
  trigger:
  - platform: zone
    entity_id: person.christian
    zone: zone.home
    event: leave
  - platform: zone
    entity_id: person.felicia
    zone: zone.home
    event: leave
  condition:
  - condition: not
    conditions:
    - condition: zone
      entity_id: person.christian
      zone: zone.home
  - condition: not
    conditions:
    - condition: zone
      entity_id: person.felicia
      zone: zone.home
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.been_home
  mode: single
- id: '1618431144975'
  alias: Kitchen - Off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: db06330462a9c0236cf4942a2bf2f843
    entity_id: binary_sensor.kitchen_sensor
    domain: binary_sensor
    for:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - service: light.turn_off
    target:
      area_id: e4cd392f3436439681504b0610b28b1d
    data: {}
  mode: single
- id: '1618432744438'
  alias: Kitchen - On
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: db06330462a9c0236cf4942a2bf2f843
    entity_id: binary_sensor.kitchen_sensor
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: input_boolean.night_mode
    state: 'off'
  action:
  - service: light.turn_on
    data: {}
    target:
      area_id: e4cd392f3436439681504b0610b28b1d
  mode: single
- id: '1618593947896'
  alias: Burglar Alarm
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: db06330462a9c0236cf4942a2bf2f843
    entity_id: binary_sensor.kitchen_sensor
    domain: binary_sensor
  - type: motion
    platform: device
    device_id: 1676fc84015df0dfd79488157a70b6c1
    entity_id: binary_sensor.stairs_sensor
    domain: binary_sensor
  condition:
  - condition: not
    conditions:
    - condition: zone
      entity_id: person.christian
      zone: zone.home
    - condition: zone
      entity_id: person.felicia
      zone: zone.home
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - service: notify.mobile_app_oneplus_8pro_chrille
    data:
      title: ALERT - Burglar Alarm
      message: Sensors detected motion!
  - service: notify.mobile_app_ac2003
    data:
      title: ALERT - Burglar Alarm
      message: Sensors detected motion!
  mode: single
- id: '1619886667783'
  alias: Raspberry Health - Fan - On
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.processor_temperature
    for: 00:01:00
    above: '50'
  condition: []
  action:
  - type: turn_on
    device_id: 6e6a02b66d3f3a9bb755aa52f4de1ee0
    entity_id: switch.fan
    domain: switch
  mode: single
- id: '1619886740896'
  alias: Raspberry Health - Fan - Off
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.processor_temperature
    below: '40'
    for: 00:01:00
  condition: []
  action:
  - type: turn_off
    device_id: 6e6a02b66d3f3a9bb755aa52f4de1ee0
    entity_id: switch.fan
    domain: switch
  mode: single
