---
- id: "1577555518352"
  alias: Home - Off
  description: ""
  trigger:
    - platform: state
      entity_id: input_boolean.someone_home
      from: "on"
      to: "off"
  condition: []
  action:
    - service: light.turn_off
      target:
        area_id:
          - 14c52f1d72d94a29a745d0a400806c3a
          - e4cd392f3436439681504b0610b28b1d
          - 5c8d6d678e49498a9e77ff541ec6fad1
    - service: media_player.turn_off
      target:
        area_id:
          - 72f600fc787e479eaf6ce20ac1df415b
        device_id:
          - 45806b6577db034d108d0ef352480539
          - 4bdf051aaa818b21fe2f85cdfc04629c
    - service: switch.turn_off
      target:
        area_id: a13da43aa35f4548a72c6e44312a414a
    - choose:
        - conditions:
            - condition: state
              entity_id: media_player.living_room_tv
              state: "on"
          sequence:
            - service: media_player.turn_off
              target:
                device_id:
                  - d545f28ac62c0ccbde8daa21a2ebe1c4
      default: []
    - service: media_player.media_stop
      target:
        entity_id: media_player.living_room
  mode: single
- id: "1577565666489"
  alias: Home - On
  description: ""
  trigger:
    - platform: state
      entity_id: input_boolean.someone_home
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
  action:
    - data: {}
      service: light.turn_on
      target:
        area_id: e4cd392f3436439681504b0610b28b1d
  mode: single
- id: "1577566232007"
  alias: Play Music - Ring
  description: ""
  trigger:
    - from: offhook
      platform: state
      to: idle
      entity_id: sensor.in2023_phone_state
  condition:
    - condition: zone
      entity_id: person.christian
      zone: zone.home
    - condition: state
      entity_id: media_player.spotify_christian_bilevits
      state: paused
    - condition: state
      entity_id: sensor.ac2003_telefonstatus
      state: offhook
  action:
    - service: media_player.media_play
      target:
        entity_id: media_player.spotify_christian_bilevits
  mode: single
- id: "1577566320646"
  alias: Pause Music - Ring
  description: ""
  trigger:
    - platform: state
      to: offhook
      entity_id: sensor.in2023_phone_state
  condition:
    - condition: zone
      entity_id: person.christian
      zone: zone.home
    - condition: state
      entity_id: media_player.spotify_christian_bilevits
      state: playing
  action:
    - service: media_player.media_pause
      target:
        entity_id:
          - media_player.spotify_christian_bilevits
  mode: single
- id: "1611609131335"
  alias: Gaming - On
  description: ""
  trigger:
    - platform: state
      entity_id: device_tracker.stadia_a2c2
      to: home
      from: not_home
  condition: []
  action:
    - service: remote.turn_on
      target:
        entity_id: remote.living_room_remote
    - wait_for_trigger:
        - platform: device
          device_id: d545f28ac62c0ccbde8daa21a2ebe1c4
          domain: media_player
          entity_id: media_player.living_room_tv
          type: turned_on
          for:
            hours: 0
            minutes: 0
            seconds: 3
            milliseconds: 0
    - service: media_player.select_source
      data:
        source: HDMI 4
      target:
        device_id: d545f28ac62c0ccbde8daa21a2ebe1c4
  mode: single
- id: "1613827164291"
  alias: Felicia Paus Music
  description: ""
  trigger:
    - platform: state
      entity_id: sensor.ac2003_telefonstatus
      to: offhook
  condition:
    - condition: zone
      entity_id: person.felicia
      zone: zone.home
    - condition: device
      device_id: 4bdf051aaa818b21fe2f85cdfc04629c
      domain: media_player
      entity_id: media_player.living_room
      type: is_playing
  action:
    - service: media_player.media_pause
      data: {}
      target:
        device_id: 4bdf051aaa818b21fe2f85cdfc04629c
  mode: single
- id: "1613827263890"
  alias: Felicia Play Music
  description: ""
  trigger:
    - platform: state
      entity_id: sensor.ac2003_telefonstatus
      from: offhook
      to: idle
  condition:
    - condition: zone
      entity_id: person.felicia
      zone: zone.home
    - condition: device
      device_id: 4bdf051aaa818b21fe2f85cdfc04629c
      domain: media_player
      entity_id: media_player.living_room
      type: is_paused
    - condition: state
      entity_id: sensor.in2023_phone_state
      state: offhook
  action:
    - service: media_player.media_play
      data: {}
      target:
        device_id: 4bdf051aaa818b21fe2f85cdfc04629c
  mode: single
- id: "1618177610102"
  alias: Night Light - Stairs - On
  description: ""
  trigger:
    - type: motion
      platform: device
      device_id: 1676fc84015df0dfd79488157a70b6c1
      entity_id: binary_sensor.stairs_sensor
      domain: binary_sensor
  condition:
    - condition: state
      entity_id: input_boolean.night_mode
      state: "on"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.adaptive_lighting_adapt_brightness_kitchen
    - type: turn_on
      device_id: ea02134afc6d69b0da1921c9af86bcb5
      entity_id: light.ceiling_toilet
      domain: light
      brightness_pct: 2
  mode: single
- id: "1618177885328"
  alias: Night Light - Kitchen - On
  description: ""
  trigger:
    - type: motion
      platform: device
      device_id: db06330462a9c0236cf4942a2bf2f843
      entity_id: binary_sensor.kitchen_sensor
      domain: binary_sensor
  condition:
    - condition: state
      entity_id: input_boolean.night_mode
      state: "on"
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.adaptive_lighting_adapt_brightness_kitchen
    - type: turn_on
      device_id: ea02134afc6d69b0da1921c9af86bcb5
      entity_id: light.ceiling_toilet
      domain: light
      brightness_pct: 2
  mode: single
- id: "1618178644833"
  alias: Night Light - Off
  description: ""
  trigger:
    - type: no_motion
      platform: device
      device_id: db06330462a9c0236cf4942a2bf2f843
      entity_id: binary_sensor.kitchen_sensor
      domain: binary_sensor
      for:
        hours: 0
        minutes: 6
        seconds: 0
        milliseconds: 0
  condition:
    - type: is_no_motion
      condition: device
      device_id: db06330462a9c0236cf4942a2bf2f843
      entity_id: binary_sensor.kitchen_sensor
      domain: binary_sensor
    - condition: numeric_state
      attribute: brightness
      above: "1"
      below: "10"
      entity_id: light.ceiling_toilet
    - condition: state
      entity_id: input_boolean.night_mode
      state: "on"
  action:
    - type: turn_off
      device_id: ea02134afc6d69b0da1921c9af86bcb5
      entity_id: light.ceiling_toilet
      domain: light
    - delay:
        hours: 0
        minutes: 0
        seconds: 5
        milliseconds: 0
    - service: switch.turn_on
      target:
        entity_id: switch.adaptive_lighting_adapt_brightness_kitchen
  mode: single
- id: "1618230174554"
  alias: Night Mode - Toggle
  description: ""
  trigger:
    - platform: time
      at: "23:30"
    - platform: time
      at: 06:30
  condition: []
  action:
    - choose:
        - conditions:
            - condition: time
              after: "23:29"
              before: 06:29
          sequence:
            - service: input_boolean.turn_on
              target:
                entity_id: input_boolean.night_mode
      default:
        - service: input_boolean.turn_off
          target:
            entity_id: input_boolean.night_mode
  mode: single
- id: "1618341675693"
  alias: Someone Home - On
  description: ""
  trigger:
    - platform: zone
      entity_id: person.christian
      zone: zone.home
      event: enter
    - platform: zone
      entity_id: person.felicia
      zone: zone.home
      event: enter
  condition: []
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.someone_home
  mode: single
- id: "1618341855293"
  alias: Someone Home - Off
  description: ""
  trigger:
    - platform: zone
      entity_id: person.christian
      zone: zone.home
      event: leave
    - platform: zone
      entity_id: person.felicia
      zone: zone.home
      event: leave
  condition:
    - condition: not
      conditions:
        - condition: zone
          entity_id: person.christian
          zone: zone.home
    - condition: not
      conditions:
        - condition: zone
          entity_id: person.felicia
          zone: zone.home
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.someone_home
  mode: single
- id: "1618431144975"
  alias: Kitchen - Off
  description: ""
  trigger:
    - type: no_motion
      platform: device
      device_id: db06330462a9c0236cf4942a2bf2f843
      entity_id: binary_sensor.kitchen_sensor
      domain: binary_sensor
      for:
        hours: 0
        minutes: 10
        seconds: 0
        milliseconds: 0
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    - service: light.turn_off
      target:
        area_id: e4cd392f3436439681504b0610b28b1d
      data: {}
  mode: single
- id: "1618432744438"
  alias: Kitchen - On
  description: ""
  trigger:
    - type: motion
      platform: device
      device_id: db06330462a9c0236cf4942a2bf2f843
      entity_id: binary_sensor.kitchen_sensor
      domain: binary_sensor
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: state
      entity_id: input_boolean.night_mode
      state: "off"
  action:
    - service: light.turn_on
      data: {}
      target:
        area_id: e4cd392f3436439681504b0610b28b1d
  mode: single
- id: "1618593947896"
  alias: Burglar Alarm
  description: ""
  trigger:
    - type: motion
      platform: device
      device_id: db06330462a9c0236cf4942a2bf2f843
      entity_id: binary_sensor.kitchen_sensor
      domain: binary_sensor
    - type: motion
      platform: device
      device_id: 1676fc84015df0dfd79488157a70b6c1
      entity_id: binary_sensor.stairs_sensor
      domain: binary_sensor
  condition:
    - condition: not
      conditions:
        - condition: zone
          entity_id: person.christian
          zone: zone.home
        - condition: zone
          entity_id: person.felicia
          zone: zone.home
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
  action:
    - service: notify.mobile_app_oneplus_8pro_chrille
      data:
        title: ALERT - Burglar Alarm
        message: Sensors detected motion!
    - service: notify.mobile_app_ac2003
      data:
        title: ALERT - Burglar Alarm
        message: Sensors detected motion!
  mode: single
- id: "1619886667783"
  alias: Raspberry Health - Fan - On
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.processor_temperature
      for: 00:01:00
      above: "50"
  condition: []
  action:
    - type: turn_on
      device_id: 6e6a02b66d3f3a9bb755aa52f4de1ee0
      entity_id: switch.fan
      domain: switch
  mode: single
- id: "1619886740896"
  alias: Raspberry Health - Fan - Off
  description: ""
  trigger:
    - platform: numeric_state
      entity_id: sensor.processor_temperature
      below: "40"
      for: 00:01:00
  condition: []
  action:
    - type: turn_off
      device_id: 6e6a02b66d3f3a9bb755aa52f4de1ee0
      entity_id: switch.fan
      domain: switch
  mode: single
- id: "1620768571160"
  alias: Sleep Mode - Off
  description: ""
  trigger:
    - platform: time
      at: 06:00
    - platform: state
      from: "on"
      to: "off"
      entity_id: input_boolean.sleep_mode
    - platform: sun
      event: sunrise
  condition: []
  action:
    - service: switch.turn_off
      target:
        entity_id:
          - switch.adaptive_lighting_sleep_mode_bedroom
          - switch.adaptive_lighting_sleep_mode_kitchen
          - switch.adaptive_lighting_sleep_mode_living_room
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.sleep_mode
  mode: single
- id: "1620768721762"
  alias: Sleep Mode - On
  description: ""
  trigger:
    - platform: state
      from: "off"
      to: "on"
      entity_id: input_boolean.sleep_mode
  condition:
    - condition: time
      after: "22:00"
      before: 06:00
  action:
    - service: switch.turn_on
      target:
        entity_id:
          - switch.adaptive_lighting_sleep_mode_kitchen
          - switch.adaptive_lighting_sleep_mode_living_room
          - switch.adaptive_lighting_sleep_mode_bedroom
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.sleep_mode
  mode: single
- id: "1621112502653"
  alias: Theme Toggle
  description: ""
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
  condition: []
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: sun.sun
              state: above_horizon
          sequence:
            - service: frontend.set_theme
              data:
                name: Milky White
      default:
        - service: frontend.set_theme
          data:
            name: Kinda Dark
  mode: single
- id: "1621754049560"
  alias: Paus Music When TV starts playing
  description: ""
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      attribute: app_name
      to: Telia Play
    - platform: state
      entity_id: media_player.living_room_tv
      attribute: app_name
      to: Netflix
  condition:
    - condition: device
      device_id: d545f28ac62c0ccbde8daa21a2ebe1c4
      domain: media_player
      entity_id: media_player.living_room_tv
      type: is_on
    - condition: device
      device_id: 4bdf051aaa818b21fe2f85cdfc04629c
      domain: media_player
      entity_id: media_player.living_room
      type: is_playing
  action:
    - service: media_player.media_pause
      target:
        entity_id: media_player.living_room
  mode: single
