- id: '1577555518352'
  alias: Turn off the lights when I leave home
  description: ''
  trigger:
  - entity_id: person.christian
    event: leave
    platform: zone
    zone: zone.home
  - platform: zone
    entity_id: person.felicia
    zone: zone.home
    event: leave
  condition:
  - condition: not
    conditions:
    - condition: zone
      entity_id: person.christian
      zone: zone.home
  - condition: not
    conditions:
    - condition: zone
      entity_id: person.felicia
      zone: zone.home
  action:
  - type: turn_off
    device_id: 0ee8444f242672552cf4ad912c6a47a2
    entity_id: light.floor
    domain: light
  - device_id: 97b31d0230c54afeb1bf6ecdbbb49922
    domain: light
    entity_id: light.bed
    type: turn_off
  - device_id: f6def5b1ec034a728acc95f4c119e782
    domain: light
    entity_id: light.ceiling_desk
    type: turn_off
  - device_id: 6d1cf939784f4140b69a43dbcc6d077b
    domain: light
    entity_id: light.ceiling_sofa
    type: turn_off
  - device_id: ddcf63714c2a4c50be1e6a101708ec10
    domain: light
    entity_id: light.ceiling_bed
    type: turn_off
  - type: turn_off
    device_id: be9974f111dc5798cffa01d41de08cff
    entity_id: light.toilet
    domain: light
  - entity_id: input_boolean.been_home
    service: input_boolean.turn_off
  - data: {}
    entity_id: media_player.living_room_speaker
    service: media_player.media_stop
  mode: single
- id: '1577565166930'
  alias: Ringing Blinking Light - On
  description: ''
  trigger:
  - entity_id: sensor.in2023_phone_state
    platform: state
    to: ringing
  condition:
  - condition: zone
    entity_id: person.christian
    zone: zone.home
  - condition: device
    device_id: f6def5b1ec034a728acc95f4c119e782
    domain: light
    entity_id: light.ceiling_desk
    type: is_on
  action:
  - entity_id: script.1577563891032
    service: script.turn_on
  mode: single
- id: '1577565265648'
  alias: Ringing Blinking Light - Off
  description: ''
  trigger:
  - entity_id: sensor.in2023_phone_state
    platform: state
    to: ringing
  condition:
  - condition: zone
    entity_id: person.christian
    zone: zone.home
  - condition: device
    device_id: f6def5b1ec034a728acc95f4c119e782
    domain: light
    entity_id: light.ceiling_desk
    type: is_off
  action:
  - entity_id: script.1577564199944
    service: script.turn_on
  mode: single
- id: '1577565666489'
  alias: Home Lights On
  description: ''
  trigger:
  - platform: zone
    entity_id: person.christian
    zone: zone.home
    event: enter
  - platform: zone
    entity_id: person.felicia
    zone: zone.home
    event: enter
  condition:
  - condition: state
    entity_id: input_boolean.been_home
    state: 'off'
  action:
  - data:
      entity_id:
      - light.bed
      - light.ceiling_bed
      - light.ceiling_desk
      - light.ceiling_sofa
      - light.floor
    service: light.turn_on
  - entity_id: input_boolean.been_home
    service: input_boolean.turn_on
  mode: single
- id: '1577566232007'
  alias: Play Music - Ring
  description: ''
  trigger:
  - entity_id: sensor.in2023_phone_state
    from: offhook
    platform: state
    to: idle
  condition:
  - condition: zone
    entity_id: person.christian
    zone: zone.home
  - condition: state
    entity_id: media_player.spotify_christian_bilevits
    state: paused
  action:
  - service: script.1577565978977
  mode: single
- id: '1577566320646'
  alias: Pause Music - Ring
  description: ''
  trigger:
  - entity_id: sensor.in2023_phone_state
    platform: state
    to: offhook
  condition:
  - condition: zone
    entity_id: person.christian
    zone: zone.home
  - condition: state
    entity_id: media_player.spotify_christian_bilevits
    state: playing
  action:
  - service: script.1577566038402
  mode: single
- id: '1585561512813'
  alias: Auto turn off - Crapper
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: be9974f111dc5798cffa01d41de08cff
    entity_id: light.toilet
    domain: light
    for:
      hours: 0
      minutes: 30
      seconds: 0
  condition:
  - condition: device
    type: is_on
    device_id: be9974f111dc5798cffa01d41de08cff
    entity_id: light.toilet
    domain: light
  action:
  - type: turn_off
    device_id: be9974f111dc5798cffa01d41de08cff
    entity_id: light.toilet
    domain: light
  mode: single
- id: '1585585858395'
  alias: Turn off ceiling - Night
  description: ''
  trigger:
  - below: '-50'
    entity_id: sensor.circadian_values
    for: 00:00:00
    platform: numeric_state
  - device_id: ddcf63714c2a4c50be1e6a101708ec10
    domain: light
    entity_id: light.ceiling_bed
    for:
      hours: 0
      minutes: 0
      seconds: 1
    platform: device
    type: turned_on
  - device_id: f6def5b1ec034a728acc95f4c119e782
    domain: light
    entity_id: light.ceiling_desk
    for:
      hours: 0
      minutes: 0
      seconds: 1
    platform: device
    type: turned_on
  - device_id: 6d1cf939784f4140b69a43dbcc6d077b
    domain: light
    entity_id: light.ceiling_sofa
    for:
      hours: 0
      minutes: 0
      seconds: 1
    platform: device
    type: turned_on
  condition:
  - below: '-50'
    condition: numeric_state
    entity_id: sensor.circadian_values
  - condition: state
    entity_id: switch.circadian_lighting_circadian_brightness
    state: 'on'
  action:
  - device_id: ddcf63714c2a4c50be1e6a101708ec10
    domain: light
    entity_id: light.ceiling_bed
    type: turn_off
  - device_id: f6def5b1ec034a728acc95f4c119e782
    domain: light
    entity_id: light.ceiling_desk
    type: turn_off
  - device_id: 6d1cf939784f4140b69a43dbcc6d077b
    domain: light
    entity_id: light.ceiling_sofa
    type: turn_off
- id: '1605973279828'
  alias: Toilet - Sensor
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: db06330462a9c0236cf4942a2bf2f843
    entity_id: binary_sensor.toilet_sensor
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: input_boolean.toilet_manual
    state: 'off'
  action:
  - choose:
    - conditions:
      - condition: time
        after: '23:00'
        before: 07:00
      sequence:
      - service: light.turn_on
        data:
          kelvin: 2262
          brightness_pct: 1
          transition: 2
        entity_id: light.toilet
    default:
    - service: light.turn_on
      data:
        kelvin: 2747
        brightness_pct: 100
        transition: 2
      entity_id: light.toilet
  mode: single
- id: '1605973464792'
  alias: Toilet - Sensor - Stopped
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: db06330462a9c0236cf4942a2bf2f843
    entity_id: binary_sensor.toilet_sensor
    domain: binary_sensor
    for:
      hours: 0
      minutes: 3
      seconds: 0
  condition:
  - condition: time
    after: 07:00
    before: '23:00'
  - condition: device
    type: is_on
    device_id: be9974f111dc5798cffa01d41de08cff
    entity_id: light.toilet
    domain: light
  - condition: state
    entity_id: input_boolean.toilet_manual
    state: 'off'
  action:
  - service: light.turn_on
    data:
      kelvin: 2747
      brightness_pct: 50
      transition: 2
    entity_id: light.toilet
  mode: single
- id: '1605973519068'
  alias: Toilet - Sensor - Off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: db06330462a9c0236cf4942a2bf2f843
    entity_id: binary_sensor.toilet_sensor
    domain: binary_sensor
    for:
      hours: 0
      minutes: 4
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.toilet_manual
    state: 'off'
  action:
  - service: light.turn_off
    data:
      transition: 2
    entity_id: light.toilet
  mode: single
- id: '1606118844897'
  alias: Toilet - Manual Trigger - On
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: be9974f111dc5798cffa01d41de08cff
    entity_id: light.toilet
    domain: light
  condition:
  - type: is_no_motion
    condition: device
    device_id: db06330462a9c0236cf4942a2bf2f843
    entity_id: binary_sensor.toilet_sensor
    domain: binary_sensor
  - condition: state
    entity_id: input_boolean.toilet_manual
    state: 'off'
  action:
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.toilet_manual
  - type: turn_on
    device_id: be9974f111dc5798cffa01d41de08cff
    entity_id: light.toilet
    domain: light
    brightness_pct: 100
  mode: single
- id: '1606119045624'
  alias: Toilet - Manual Trigger - Off
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: be9974f111dc5798cffa01d41de08cff
    entity_id: light.toilet
    domain: light
  condition:
  - condition: state
    entity_id: input_boolean.toilet_manual
    state: 'on'
  action:
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.toilet_manual
  mode: single
- id: '1607243658672'
  alias: Welcome Home - Christian
  description: ''
  trigger:
  - platform: zone
    entity_id: person.christian
    zone: zone.home
    event: enter
  condition: []
  action:
  - delay: '60'
  - service: script.welcome_home_christian
    data:
      name: Christian
    entity_id: script.welcome_home_christian
  mode: single
- id: '1607244394687'
  alias: Welcome Home - Felicia
  description: ''
  trigger:
  - platform: zone
    entity_id: person.felicia
    zone: zone.home
    event: enter
  condition: []
  action:
  - delay: '60'
  - service: script.welcome_home_christian
    data:
      name: Felicia
  mode: single
