name: Home Assistant Config CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  home_assistant:
    runs-on: ubuntu-latest

    steps:
      - name: Getting config from Github
        uses: actions/checkout@v2
      - name: Copy stub files into config
        run: cp -R ./.stubs/* ./
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: |
            python -m homeassistant \
              --script check_config \
              --info all
