---
name: Home Assistant Config CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]
  schedule:
    - cron: 0 18 * * *


jobs:
  home-assistant:
    name: "Home Assistant Configuration Check for version ${{ matrix.version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["", "stable", "beta", "dev"] # Empty string to also run against current used version, specified in .HA_VERSION
    steps:
      - name: Getting config from Github
        uses: actions/checkout@v2
      - name: Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@v1.2
        with:
          secrets: ./.stubs/secrets.yaml
          version: "${{ matrix.version }}"
